server:
  port: 8002
spring:
  application:
    name: andlinks-cloud-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.22:3306/cc
    username: root
    password: andlinks
  cloud:
    refresh:
      refreshable: none                             #修复actuator和spring data jpa同时引入导致datasoure循环依赖的bug

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    

eureka:
  instance:
      prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


